<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\API.Imobiliaria.Aplicacao\API.Imobiliaria.Aplicacao.csproj" />
    <ProjectReference Include="..\API.Imobiliaria.Data\API.Imobiliaria.Data.csproj" />
  </ItemGroup>

</Project>
